.PHONY: clean All

All:
	@echo "----------Building project:[ LR3 - Debug ]----------"
	@cd "LR3" && "$(MAKE)" -f  "LR3.mk"
clean:
	@echo "----------Cleaning project:[ LR3 - Debug ]----------"
	@cd "LR3" && "$(MAKE)" -f  "LR3.mk" clean
